models:
  GPT2:
    class_name: Models.GPT2.GPT2.GPTModel
    num_params: 128M
      dtype: float32
      weights_url: openai-community/gpt2
  LLAMA_7B:
    name: Llama
    weight_url: "https://path/to/llama/7b/weights"
  LLAMA_13B:
    name: Llama
    weight_url: "https://path/to/llama/13b/weights"
  GPT_6B:
    name: GPT
    weight_url: "https://path/to/gpt/6b/weights"
  GPT_13B:
    name: GPT
    weight_url: "https://path/to/gpt/13b/weights"
